# -*- coding: utf-8 -*-
"""20240608.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vJnoIup-3t-UNREMQ5e8ZvSCw-qvMRxM
"""

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlextend.preprocessing import TransactionEncoder

data = {
    'TransactionID': [1,2,3,4,5],
    'Items': [
        ['Milk', 'Bread','Apple','Banana'],
        ['Milk','Apple','Bread', 'Banana'],
        ['Milk','Apple','Bread'],
        ['Apple', 'Banana'],
        ['Milk','Bread']
    ],
    df = pd.DataFrame(data)
    df['Items'] = df['Items'].apply(frozenset)
    print(df['Items'])


    transactions = df['Items'].tolist()
    print(transactions)

    te = TransactionEncoder()
    te_ary = te.fit(transactions).transform(transactions)
    print(te_ary)

    #convert to dataframe

    df_encoded = pd.DataFrame(te_ary, columns=te.columns_)
    print(df_encoded)



    frequent_itemsets = apriori(df_encoded, min_support=0.4, use_colnames=True)
    print(frequent_itemsets)

    rules = association_rules(frequent_itemsets, metric= "lift", min_threshold=1.2)
    print(rules)
}

